experiment_types:
  - Wifi
  - Ethernet
  - 3G
  - DSRC
  - IREEL
resources:
  - identifier: r1
    nodes:
      - n1
      - n2
      - n3
      - n4
      - n5
      - n6
      - n7
      - n8
      - n9
  - identifier: r2
    nodes:
      - n11
      - n12
      - n13
      - n14
      - n15
      - n16
      - n17
      - n18
      - n19
  - identifier: r3
    nodes:
      - n21
      - n22
      - n22
      - n24
      - n25
      - n26
      - n27
      - n28
      - n29
gcal:
  account: jhong@incontext.com.au
  password: Loyalty225
  calendars:
    - identifier: v8i5bns2ndjajh1i1bbn97f520%40group.calendar.google.com
      private_address: http://www.google.com/calendar/embed?src=v8i5bns2ndjajh1i1bbn97f520%40group.calendar.google.com&ctz=Australia/Sydney&pvttk=6d15610c34418191a0b91b12435aabf5
      location: 25 Garden St Eveleigh New South Wales 2015
