experiment_types:
  - Wifi
  - Ethernet
  - 3G
  - DSRC
  - IREEL
resources:
  - identifier: r1
    gcal: v8i5bns2ndjajh1i1bbn97f520@group.calendar.google.com
    pvttk: 6d15610c34418191a0b91b12435aabf5
    colour: "#2F6213"
    nodes:
      - n1
      - n2
      - n3
      - n4
      - n5
      - n6
      - n7
      - n8
      - n9
  - identifier: r2
    gcal: ssitncbuo0pj8qt0uiurkqjqc4@group.calendar.google.com
    colour: "#113F47"
    pvttk: 2965c0dc31e3da863d19b27f4eb9be88
    nodes:
      - n11
      - n12
      - n13
      - n14
      - n15
      - n16
      - n17
      - n18
      - n19
  - identifier: r3
    gcal: 9f4q03c2upsrcpogg9bt3k8q6g@group.calendar.google.com
    pvttk: c7236e0005ed2306c1b93bc8d7614a86
    colour: "#182C57"
    nodes:
      - n21
      - n22
      - n22
      - n24
      - n25
      - n26
      - n27
      - n28
      - n29
gcal:
  account: jhong@incontext.com.au
  password: Loyalty225
  ctz: Australia/Sydney
  location: 25 Garden St Eveleigh New South Wales 2015
