development:
  git_dir: /var/cache/git/development/
  experiment_types:
    - Wifi
    - Ethernet
    - 3G
    - DSRC
    - IREEL
  resources:
    - node1
    - node2
    - node3

test:
  git_dir: /var/cache/git/test/
  experiment_types:
    - Wifi
    - Ethernet
    - 3G
    - DSRC
    - IREEL

production:
  git_dir: /var/cache/git/production/
  experiment_types:
    - Wifi
    - Ethernet
    - 3G
    - DSRC
    - IREEL
